/**
 * Generated by `build/vendor-assets.ts` from the Lucide icons actually referenced under
 * `.claude-design/point-and-shoot/ui_kits/` and `components/`. Each name maps to a
 * `#icon-<name>` symbol id in `src/shared/design/icons.svg`.
 */
export type IconName =
  | "arrow-down"
  | "arrow-up"
  | "camera"
  | "crosshair"
  | "list-checks"
  | "message-square-plus"
  | "pencil"
  | "settings"
  | "trash-2";
