/*
 * GENERATED FILE — do not edit by hand.
 * Regenerate with `deno task tokens`. Edits belong upstream in
 * .claude-design/point-and-shoot/tokens/, re-exported as a whole bundle (see docs/design.md).
 *
 * Design bundle: namespace=PointShootDesignSystem_5498d1 contentHash=2ed2f2a9a1d9f5a67189eb42cdef0c16192474f4
 */

/** Every custom-property token name defined in `tokens.css`. */
export type TokenName =
  | "font-display"
  | "font-body"
  | "font-mono"
  | "black"
  | "gray-950"
  | "gray-900"
  | "gray-850"
  | "gray-800"
  | "gray-700"
  | "gray-600"
  | "gray-500"
  | "gray-400"
  | "gray-300"
  | "gray-200"
  | "gray-100"
  | "gray-50"
  | "white"
  | "blue-700"
  | "blue-600"
  | "blue-500"
  | "blue-400"
  | "blue-100"
  | "green-500"
  | "amber-500"
  | "red-500"
  | "bg-canvas"
  | "bg-surface"
  | "bg-surface-raised"
  | "bg-elevated"
  | "bg-overlay"
  | "bg-inset"
  | "border-subtle"
  | "border-default"
  | "border-strong"
  | "text-primary"
  | "text-secondary"
  | "text-tertiary"
  | "text-inverse"
  | "text-disabled"
  | "accent"
  | "accent-hover"
  | "accent-active"
  | "accent-subtle"
  | "accent-contrast"
  | "accent-text"
  | "success"
  | "warning"
  | "danger"
  | "focus-ring"
  | "scrim"
  | "text-2xs"
  | "text-xs"
  | "text-sm"
  | "text-base"
  | "text-md"
  | "text-lg"
  | "text-xl"
  | "text-2xl"
  | "text-3xl"
  | "text-4xl"
  | "leading-tight"
  | "leading-snug"
  | "leading-normal"
  | "leading-relaxed"
  | "tracking-tight"
  | "tracking-normal"
  | "tracking-wide"
  | "tracking-wider"
  | "weight-regular"
  | "weight-medium"
  | "weight-semibold"
  | "weight-bold"
  | "space-0"
  | "space-1"
  | "space-2"
  | "space-3"
  | "space-4"
  | "space-5"
  | "space-6"
  | "space-8"
  | "space-10"
  | "space-12"
  | "space-16"
  | "space-20"
  | "space-24"
  | "radius-xs"
  | "radius-sm"
  | "radius-md"
  | "radius-lg"
  | "radius-xl"
  | "radius-full"
  | "container-max"
  | "shadow-sm"
  | "shadow-md"
  | "shadow-lg"
  | "shadow-focus"
  | "glow-accent"
  | "ease-standard"
  | "ease-out"
  | "duration-fast"
  | "duration-base"
  | "duration-slow"
  | "blur-panel";

/**
 * Returns the `var(--token)` reference for a token name, so a typo is a type error instead of a
 * silently-empty CSS variable.
 *
 * @param name - A token name, without the leading `--`.
 * @returns The `var(--name)` CSS value.
 * @example token("accent") // => "var(--accent)"
 */
export function token(name: TokenName): string {
  return `var(--${name})`;
}
